defaults:
  - /base
  - base_planner
  - _self_

type: diffusion
checkpoint_path: results/train_diffusion/run/2026-08-23_19-29-04/final_checkpoint.pt
replan_every: 8
target_return: 1.2
device: null                # null → auto (cuda if available, else cpu)

warm_start: True
noise_steps: 10
use_belief: True
use_return: True
use_egocentric: True