hydra:
  run:
    dir: results/${hydra.job.name}/run/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: results/${hydra.job.name}/sweep/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ''

defaults:
  - base
  - diffusion_model
  - planner: diffusion
  - _self_

n_timesteps: 100
scenario_idx: 0
